### ISSUE TITLE
USER STORY: As a Site User I can view the pizza menu online so I can know the ingredients and prices

### ISSUE THREAD

**Issue by RubemJanoni** [RubemJanoni/Project-PP5#1]
EPIC: Menu page creation

As a **Site User** I can **view the pizza menu online** so that **I can know the ingredients and prices**

  
**Acceptance Criteria**

- [ ] Menu form has title, description, image, price and ingredients.
- [ ] The User can add as many products as needed
- [ ] The User can preview the selected products in the cart.
- [ ] The User can select the product by category

**Tasks**

Task 1: Design and Implement the menu page
Task 2: Implement upload, add, edit, remove funcionality
Task 3: Add validation and error handling
Task 4: Test menu funcionality
