### ISSUE TITLE
USER STORY: As a Site User I can make a payment online so that I can get an order fast and online

### ISSUE THREAD

**Issue by RubemJanoni** [RubemJanoni/Project-PP5#4]
EPIC: Check out page creation

As a **Site User** I can **make a payment online** so that **I can get an order fast and online**

  
**Acceptance Criteria**

- [ ] Checkout form has title, description, image, total and payment methods.
- [ ] The User can pay by card
- [ ] The User can receive a notification

**Tasks**

Task 1: Design and Implement the checkout  page
Task 2: Implement payments funcionality
Task 3: Add validation and error handling
Task 4: Test payment funcionality
